# Numpy

In [1]:
import numpy as np

In [2]:
array_1 = np.array([1,2,3])

In [3]:
array_1

array([1, 2, 3])

In [4]:
type(array_1)

numpy.ndarray

In [7]:
array_2 = np.array([[10,20,30],[100,30,50]])

In [8]:
array_2

array([[ 10,  20,  30],
       [100,  30,  50]])

In [13]:
array_3 = np.array([[[10,20,30],[10,20,30],[10,20,30],[10,20,30],[10,20,30]]])

In [14]:
array_3

array([[[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]]])

In [16]:
array_2.shape

(2, 3)

In [18]:
array_3.shape

(1, 5, 3)

In [19]:
array_2.ndim

2

In [20]:
array_3.ndim

3

In [21]:
array_2.size

6

In [22]:
array_1.size

3

In [23]:
import pandas as pd

In [26]:
df1 = pd.DataFrame(array_1)

In [27]:
df1

0
0  1
1  2
2  3

In [32]:
df3 = pd.DataFrame(array_3.reshape(3,5))

In [33]:
df3

0   1   2   3   4
0  10  20  30  10  20
1  30  10  20  30  10
2  20  30  10  20  30