# Numpy

In [1]:
import numpy as np

In [2]:
array_1 = np.array([1,2,3])

In [3]:
array_1

array([1, 2, 3])

In [4]:
type(array_1)

numpy.ndarray

In [7]:
array_2 = np.array([[10,20,30],[100,30,50]])

In [8]:
array_2

array([[ 10,  20,  30],
       [100,  30,  50]])

In [13]:
array_3 = np.array([[[10,20,30],[10,20,30],[10,20,30],[10,20,30],[10,20,30]]])

In [14]:
array_3

array([[[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]]])

In [16]:
array_2.shape

(2, 3)

In [18]:
array_3.shape

(1, 5, 3)

In [19]:
array_2.ndim

2

In [20]:
array_3.ndim

3

In [21]:
array_2.size

6

In [22]:
array_1.size

3

In [23]:
import pandas as pd

In [26]:
df1 = pd.DataFrame(array_1)

In [27]:
df1

0
0  1
1  2
2  3

In [32]:
df3 = pd.DataFrame(array_3.reshape(3,5))

In [33]:
df3

0   1   2   3   4
0  10  20  30  10  20
1  30  10  20  30  10
2  20  30  10  20  30

In [34]:
ar_zeros = np.zeros(5)

In [35]:
ar_zeros

array([0., 0., 0., 0., 0.])

In [36]:
ar_ones = np.ones(5)

In [37]:
ar_ones

array([1., 1., 1., 1., 1.])

In [38]:
ar_zeros.shape

(5,)

In [39]:
ar_ones.shape

(5,)

In [40]:
my_array = np.arange(1,20,3)

In [41]:
my_array

array([ 1,  4,  7, 10, 13, 16, 19])

In [42]:
rand_array = np.random.randint(0,10,5)

In [43]:
rand_array

array([4, 6, 9, 7, 4])

In [44]:
rand_array_2 = np.random.random(5)

In [45]:
rand_array_2

array([0.91206664, 0.68291388, 0.74720036, 0.42694874, 0.1483367 ])

In [46]:
rand_array_3 = np.random.rand(5)

In [47]:
rand_array_3

array([0.81527412, 0.82004725, 0.56725068, 0.56966726, 0.30110969])

In [48]:
gg = np.arange(10,20)

In [49]:
gg


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
rand_array_6 = np.random.randint(20,100,size = (3,4,5,6,))
rand_array_6


array([[[[41, 40, 54, 94, 22, 41],
         [79, 55, 54, 56, 96, 50],
         [36, 22, 97, 63, 80, 91],
         [30, 25, 72, 91, 30, 54],
         [76, 40, 69, 99, 96, 58]],

        [[62, 59, 40, 97, 55, 97],
         [95, 55, 21, 45, 66, 27],
         [88, 87, 23, 47, 41, 28],
         [42, 72, 64, 32, 39, 24],
         [89, 77, 75, 24, 49, 58]],

        [[72, 39, 81, 62, 55, 52],
         [87, 82, 25, 57, 60, 57],
         [95, 68, 61, 49, 42, 26],
         [66, 67, 39, 28, 38, 78],
         [22, 91, 86, 96, 43, 68]],

        [[56, 68, 54, 34, 36, 93],
         [64, 23, 34, 94, 36, 78],
         [25, 79, 73, 24, 73, 78],
         [55, 21, 32, 68, 80, 53],
         [63, 66, 30, 91, 96, 48]]],


       [[[79, 91, 80, 41, 84, 20],
         [66, 70, 46, 29, 54, 67],
         [86, 55, 42, 52, 85, 29],
         [83, 88, 38, 58, 82, 98],
         [40, 38, 41, 93, 72, 99]],

        [[70, 86, 66, 66, 91, 83],
         [77, 28, 70, 68, 53, 58],
         [99, 74, 79, 30, 80, 83],
        

In [52]:
rand_array_6[0]

array([[[41, 40, 54, 94, 22, 41],
        [79, 55, 54, 56, 96, 50],
        [36, 22, 97, 63, 80, 91],
        [30, 25, 72, 91, 30, 54],
        [76, 40, 69, 99, 96, 58]],

       [[62, 59, 40, 97, 55, 97],
        [95, 55, 21, 45, 66, 27],
        [88, 87, 23, 47, 41, 28],
        [42, 72, 64, 32, 39, 24],
        [89, 77, 75, 24, 49, 58]],

       [[72, 39, 81, 62, 55, 52],
        [87, 82, 25, 57, 60, 57],
        [95, 68, 61, 49, 42, 26],
        [66, 67, 39, 28, 38, 78],
        [22, 91, 86, 96, 43, 68]],

       [[56, 68, 54, 34, 36, 93],
        [64, 23, 34, 94, 36, 78],
        [25, 79, 73, 24, 73, 78],
        [55, 21, 32, 68, 80, 53],
        [63, 66, 30, 91, 96, 48]]])

In [53]:
rand_array_6[1]

array([[[79, 91, 80, 41, 84, 20],
        [66, 70, 46, 29, 54, 67],
        [86, 55, 42, 52, 85, 29],
        [83, 88, 38, 58, 82, 98],
        [40, 38, 41, 93, 72, 99]],

       [[70, 86, 66, 66, 91, 83],
        [77, 28, 70, 68, 53, 58],
        [99, 74, 79, 30, 80, 83],
        [40, 81, 32, 48, 28, 84],
        [32, 56, 38, 53, 58, 62]],

       [[55, 66, 36, 79, 39, 82],
        [79, 55, 27, 67, 24, 75],
        [96, 22, 89, 81, 80, 51],
        [33, 31, 93, 41, 59, 50],
        [45, 82, 77, 53, 40, 65]],

       [[60, 30, 71, 36, 71, 32],
        [59, 48, 54, 25, 96, 40],
        [52, 73, 49, 44, 54, 24],
        [55, 69, 34, 86, 59, 30],
        [69, 33, 67, 56, 62, 47]]])

In [54]:
rand_array_6[1][0]

array([[79, 91, 80, 41, 84, 20],
       [66, 70, 46, 29, 54, 67],
       [86, 55, 42, 52, 85, 29],
       [83, 88, 38, 58, 82, 98],
       [40, 38, 41, 93, 72, 99]])

In [55]:
rand_array_6[0].shape

(4, 5, 6)

In [56]:
rand_array_6[:,:,:3]

array([[[[41, 40, 54, 94, 22, 41],
         [79, 55, 54, 56, 96, 50],
         [36, 22, 97, 63, 80, 91]],

        [[62, 59, 40, 97, 55, 97],
         [95, 55, 21, 45, 66, 27],
         [88, 87, 23, 47, 41, 28]],

        [[72, 39, 81, 62, 55, 52],
         [87, 82, 25, 57, 60, 57],
         [95, 68, 61, 49, 42, 26]],

        [[56, 68, 54, 34, 36, 93],
         [64, 23, 34, 94, 36, 78],
         [25, 79, 73, 24, 73, 78]]],


       [[[79, 91, 80, 41, 84, 20],
         [66, 70, 46, 29, 54, 67],
         [86, 55, 42, 52, 85, 29]],

        [[70, 86, 66, 66, 91, 83],
         [77, 28, 70, 68, 53, 58],
         [99, 74, 79, 30, 80, 83]],

        [[55, 66, 36, 79, 39, 82],
         [79, 55, 27, 67, 24, 75],
         [96, 22, 89, 81, 80, 51]],

        [[60, 30, 71, 36, 71, 32],
         [59, 48, 54, 25, 96, 40],
         [52, 73, 49, 44, 54, 24]]],


       [[[90, 27, 78, 71, 54, 93],
         [24, 60, 88, 76, 44, 56],
         [20, 68, 51, 55, 69, 46]],

        [[83, 74, 59, 20, 37, 31]

In [60]:
ar1 = np.ones(4)

In [61]:
ar1

array([1., 1., 1., 1.])

In [62]:
ar2 = np.zeros(4)

In [63]:
ar1 + ar2

array([1., 1., 1., 1.])

In [64]:
ar3 = np.array([1,2,3,4])

In [65]:
ar4 = np.array([5,6,7,8])

In [66]:
ar3 * ar4

array([ 5, 12, 21, 32])

In [73]:
ar5 = np.array([[1,2,3,4],[5,6,7,8]])


In [74]:
ar5 *ar3

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

In [75]:
ar3 * ar5

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

In [76]:
ar4 / ar3

array([5.        , 3.        , 2.33333333, 2.        ])

In [77]:
ar4 // ar3

array([5, 3, 2, 2])

In [78]:
ar3 **2

array([ 1,  4,  9, 16])

In [79]:
ar4 **2

array([25, 36, 49, 64])

In [80]:
ar3 % 2

array([1, 0, 1, 0])

In [81]:
np.exp(ar3)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [82]:
np.log(ar3)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [86]:
np.sum(ar3) , sum(ar4)

(10, 26)

In [85]:
ar3

array([1, 2, 3, 4])

In [87]:
np.mean(ar3)

2.5

In [88]:
np.max(ar3)

4

In [89]:
np.min(ar3)

1

In [90]:
np.std(ar3)

1.118033988749895

In [91]:
np.var(ar3)

1.25

In [92]:
np.sqrt(ar3)

array([1.        , 1.41421356, 1.73205081, 2.        ])