# Numpy

In [ ]:
import numpy as np

In [ ]:
array_1 = np.array([1,2,3])

In [ ]:
array_1

array([1, 2, 3])

In [ ]:
type(array_1)

numpy.ndarray

In [ ]:
array_2 = np.array([[10,20,30],[100,30,50]])

In [ ]:
array_2

array([[ 10,  20,  30],
       [100,  30,  50]])

In [ ]:
array_3 = np.array([[[10,20,30],[10,20,30],[10,20,30],[10,20,30],[10,20,30]]])

In [ ]:
array_3

array([[[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]]])

In [ ]:
array_2.shape

(2, 3)

In [ ]:
array_3.shape

(1, 5, 3)

In [ ]:
array_2.ndim

2

In [ ]:
array_3.ndim

3

In [ ]:
array_2.size

6

In [ ]:
array_1.size

3

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame(array_1)

In [ ]:
df1

0
0  1
1  2
2  3

In [ ]:
df3 = pd.DataFrame(array_3.reshape(3,5))

In [ ]:
df3

0   1   2   3   4
0  10  20  30  10  20
1  30  10  20  30  10
2  20  30  10  20  30

In [ ]:
ar_zeros = np.zeros(5)

In [ ]:
ar_zeros

array([0., 0., 0., 0., 0.])

In [ ]:
ar_ones = np.ones(5)

In [ ]:
ar_ones

array([1., 1., 1., 1., 1.])

In [ ]:
ar_zeros.shape

(5,)

In [ ]:
ar_ones.shape

(5,)

In [ ]:
my_array = np.arange(1,20,3)

In [ ]:
my_array

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
rand_array = np.random.randint(0,10,5)

In [ ]:
rand_array

array([8, 2, 6, 2, 9])

In [ ]:
rand_array_2 = np.random.random(5)

In [ ]:
rand_array_2

array([0.15962072, 0.83177213, 0.43623753, 0.9787309 , 0.58953367])

In [ ]:
rand_array_3 = np.random.rand(5)

In [ ]:
rand_array_3

array([0.76445063, 0.16850519, 0.99361796, 0.90558174, 0.39461991])

In [ ]:
gg = np.arange(10,20)

In [ ]:
gg


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
rand_array_6 = np.random.randint(20,100,size = (3,4,5,6,))
rand_array_6


array([[[[45, 79, 95, 98, 94, 55],
         [45, 85, 71, 25, 45, 66],
         [71, 85, 70, 89, 69, 39],
         [57, 32, 53, 71, 87, 41],
         [52, 80, 45, 98, 44, 70]],

        [[25, 64, 87, 45, 58, 89],
         [88, 88, 93, 72, 93, 81],
         [41, 37, 87, 87, 62, 34],
         [84, 73, 54, 88, 44, 35],
         [67, 57, 94, 38, 58, 69]],

        [[69, 47, 54, 94, 88, 44],
         [37, 83, 82, 96, 50, 94],
         [76, 71, 79, 29, 20, 95],
         [88, 73, 57, 79, 59, 94],
         [62, 66, 45, 76, 72, 27]],

        [[58, 84, 82, 60, 20, 86],
         [93, 80, 89, 79, 93, 65],
         [42, 95, 90, 84, 67, 97],
         [45, 63, 52, 85, 53, 89],
         [68, 39, 27, 40, 95, 86]]],


       [[[75, 58, 92, 40, 54, 56],
         [23, 92, 72, 86, 78, 20],
         [68, 36, 71, 20, 99, 77],
         [77, 53, 76, 53, 63, 96],
         [24, 20, 66, 73, 57, 91]],

        [[86, 46, 78, 82, 71, 99],
         [72, 83, 24, 41, 39, 86],
         [67, 80, 61, 67, 51, 21],
        

In [ ]:
rand_array_6[0]

array([[[45, 79, 95, 98, 94, 55],
        [45, 85, 71, 25, 45, 66],
        [71, 85, 70, 89, 69, 39],
        [57, 32, 53, 71, 87, 41],
        [52, 80, 45, 98, 44, 70]],

       [[25, 64, 87, 45, 58, 89],
        [88, 88, 93, 72, 93, 81],
        [41, 37, 87, 87, 62, 34],
        [84, 73, 54, 88, 44, 35],
        [67, 57, 94, 38, 58, 69]],

       [[69, 47, 54, 94, 88, 44],
        [37, 83, 82, 96, 50, 94],
        [76, 71, 79, 29, 20, 95],
        [88, 73, 57, 79, 59, 94],
        [62, 66, 45, 76, 72, 27]],

       [[58, 84, 82, 60, 20, 86],
        [93, 80, 89, 79, 93, 65],
        [42, 95, 90, 84, 67, 97],
        [45, 63, 52, 85, 53, 89],
        [68, 39, 27, 40, 95, 86]]])

In [ ]:
rand_array_6[1]

array([[[75, 58, 92, 40, 54, 56],
        [23, 92, 72, 86, 78, 20],
        [68, 36, 71, 20, 99, 77],
        [77, 53, 76, 53, 63, 96],
        [24, 20, 66, 73, 57, 91]],

       [[86, 46, 78, 82, 71, 99],
        [72, 83, 24, 41, 39, 86],
        [67, 80, 61, 67, 51, 21],
        [72, 39, 67, 83, 83, 87],
        [21, 85, 21, 72, 21, 78]],

       [[91, 28, 98, 22, 31, 88],
        [95, 71, 60, 33, 48, 51],
        [22, 59, 39, 48, 68, 47],
        [31, 27, 41, 23, 22, 93],
        [45, 48, 30, 96, 66, 92]],

       [[59, 90, 95, 61, 94, 26],
        [81, 97, 44, 51, 66, 39],
        [93, 23, 88, 20, 79, 85],
        [75, 92, 48, 64, 44, 67],
        [48, 58, 27, 21, 46, 63]]])

In [ ]:
rand_array_6[1][0]

array([[75, 58, 92, 40, 54, 56],
       [23, 92, 72, 86, 78, 20],
       [68, 36, 71, 20, 99, 77],
       [77, 53, 76, 53, 63, 96],
       [24, 20, 66, 73, 57, 91]])

In [ ]:
rand_array_6[0].shape

(4, 5, 6)

In [ ]:
rand_array_6[:,:,:3]

array([[[[45, 79, 95, 98, 94, 55],
         [45, 85, 71, 25, 45, 66],
         [71, 85, 70, 89, 69, 39]],

        [[25, 64, 87, 45, 58, 89],
         [88, 88, 93, 72, 93, 81],
         [41, 37, 87, 87, 62, 34]],

        [[69, 47, 54, 94, 88, 44],
         [37, 83, 82, 96, 50, 94],
         [76, 71, 79, 29, 20, 95]],

        [[58, 84, 82, 60, 20, 86],
         [93, 80, 89, 79, 93, 65],
         [42, 95, 90, 84, 67, 97]]],


       [[[75, 58, 92, 40, 54, 56],
         [23, 92, 72, 86, 78, 20],
         [68, 36, 71, 20, 99, 77]],

        [[86, 46, 78, 82, 71, 99],
         [72, 83, 24, 41, 39, 86],
         [67, 80, 61, 67, 51, 21]],

        [[91, 28, 98, 22, 31, 88],
         [95, 71, 60, 33, 48, 51],
         [22, 59, 39, 48, 68, 47]],

        [[59, 90, 95, 61, 94, 26],
         [81, 97, 44, 51, 66, 39],
         [93, 23, 88, 20, 79, 85]]],


       [[[38, 68, 60, 97, 92, 72],
         [94, 80, 56, 71, 31, 73],
         [61, 50, 96, 57, 93, 63]],

        [[75, 56, 98, 53, 69, 59]

In [ ]:
ar1 = np.ones(4)

In [ ]:
ar1

array([1., 1., 1., 1.])

In [ ]:
ar2 = np.zeros(4)

In [ ]:
ar1 + ar2

array([1., 1., 1., 1.])

In [ ]:
ar3 = np.array([1,2,3,4])

In [ ]:
ar4 = np.array([5,6,7,8])

In [ ]:
ar3 * ar4

array([ 5, 12, 21, 32])

In [ ]:
ar5 = np.array([[1,2,3,4],[5,6,7,8]])


In [ ]:
ar5 *ar3

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

In [ ]:
ar3 * ar5

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

In [ ]:
ar4 / ar3

array([5.        , 3.        , 2.33333333, 2.        ])

In [ ]:
ar4 // ar3

array([5, 3, 2, 2])

In [ ]:
ar3 **2

array([ 1,  4,  9, 16])

In [ ]:
ar4 **2

array([25, 36, 49, 64])

In [ ]:
ar3 % 2

array([1, 0, 1, 0])

In [ ]:
np.exp(ar3)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
np.log(ar3)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.sum(ar3) , sum(ar4)

(10, 26)

In [ ]:
ar3

array([1, 2, 3, 4])

In [ ]:
np.mean(ar3)

2.5

In [ ]:
np.max(ar3)

4

In [ ]:
np.min(ar3)

1

In [ ]:
np.std(ar3)

1.118033988749895

In [ ]:
np.var(ar3)

1.25

In [ ]:
np.sqrt(ar3)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
  ar1.shape

(4,)

In [ ]:
ar1 , ar3

(array([1., 1., 1., 1.]), array([1, 2, 3, 4]))

In [ ]:
ar1 * ar3

array([1., 2., 3., 4.])

In [ ]:
ar6 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
ar6

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
ar6.shape

(2, 2, 3)

In [ ]:
ar7 = np.array([[[1,2],[4,5]],[[7,8],[10,11]]])

In [ ]:
ar7

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
ar2 > ar3

array([False, False, False, False])

In [ ]:
ar3 == ar4

array([False, False, False, False])

In [ ]:
ar3.shape < ar4.shape

False

In [ ]:
### final of NumPy ###

## Simple Sales Data Analysis

In [2]:
import numpy as np
import pandas as pd

In [5]:
from io import StringIO

data = """Date,Product,QuantitySold,UnitPrice,City
2024-01-01,Laptop,2,1200,Tehran
2024-01-01,Mouse,5,25,Tehran
2024-01-02,Keyboard,3,75,Mashhad
2024-01-02,Monitor,1,300,Isfahan
2024-01-03,Laptop,1,1200,Tabriz
2024-01-03,External Hard Drive,2,100,Tehran
2024-01-04,Mouse,4,25,Shiraz
2024-01-04,Laptop,1,1200,Mashhad
2024-01-05,Keyboard,2,75,Isfahan
2024-01-05,Monitor,1,300,Tehran"""

df = pd.read_csv(StringIO(data))


In [6]:
df

Date              Product  QuantitySold  UnitPrice     City
0  2024-01-01               Laptop             2       1200   Tehran
1  2024-01-01                Mouse             5         25   Tehran
2  2024-01-02             Keyboard             3         75  Mashhad
3  2024-01-02              Monitor             1        300  Isfahan
4  2024-01-03               Laptop             1       1200   Tabriz
5  2024-01-03  External Hard Drive             2        100   Tehran
6  2024-01-04                Mouse             4         25   Shiraz
7  2024-01-04               Laptop             1       1200  Mashhad
8  2024-01-05             Keyboard             2         75  Isfahan
9  2024-01-05              Monitor             1        300   Tehran

In [9]:
#Calculations - Total Revenue per Transaction
quantity_sold_np = df['QuantitySold'].to_numpy()
unit_price_np = df['UnitPrice'].to_numpy()

total_revenue_np = quantity_sold_np * unit_price_np
print("Total Revenue Array (NumPy):")
print(total_revenue_np)


Total Revenue Array (NumPy):
[2400  125  225  300 1200  200  100 1200  150  300]


In [13]:
df["TotalRevenue"] = total_revenue_np
df

Date              Product  QuantitySold  UnitPrice     City  \
0  2024-01-01               Laptop             2       1200   Tehran   
1  2024-01-01                Mouse             5         25   Tehran   
2  2024-01-02             Keyboard             3         75  Mashhad   
3  2024-01-02              Monitor             1        300  Isfahan   
4  2024-01-03               Laptop             1       1200   Tabriz   
5  2024-01-03  External Hard Drive             2        100   Tehran   
6  2024-01-04                Mouse             4         25   Shiraz   
7  2024-01-04               Laptop             1       1200  Mashhad   
8  2024-01-05             Keyboard             2         75  Isfahan   
9  2024-01-05              Monitor             1        300   Tehran   

   TotalRevenue  
0          2400  
1           125  
2           225  
3           300  
4          1200  
5           200  
6           100  
7          1200  
8           150  
9           300

In [14]:
#Analysis - Average Sales by Product

average_product_sales = df.groupby('Product')[['QuantitySold', 'TotalRevenue']].mean()
print("Average Quantity Sold and Total Revenue by Product:")
print(average_product_sales)

Average Quantity Sold and Total Revenue by Product:
                     QuantitySold  TotalRevenue
Product                                        
External Hard Drive      2.000000         200.0
Keyboard                 2.500000         187.5
Laptop                   1.333333        1600.0
Monitor                  1.000000         300.0
Mouse                    4.500000         112.5


In [20]:
#Analysis - Highest Revenue in Each City

max_revenue_city = df.groupby('City')['TotalRevenue'].max()
print("Maximum Total Revenue in Each City:")
print(max_revenue_city)
max_value = max_revenue_city.max()
max_city = max_revenue_city.idxmax()
print("MAX CITY:", max_city)
print("MAX VALUE:", max_value)

Maximum Total Revenue in Each City:
City
Isfahan     300
Mashhad    1200
Shiraz      100
Tabriz     1200
Tehran     2400
Name: TotalRevenue, dtype: int64
MAX CITY: Tehran
MAX VALUE: 2400


In [21]:
#Filtering Data For LAPTOP

laptop_sales = df[df['Product'] == 'Laptop']
print("Sales related to Laptop:")
print(laptop_sales)

Sales related to Laptop:
         Date Product  QuantitySold  UnitPrice     City  TotalRevenue
0  2024-01-01  Laptop             2       1200   Tehran          2400
4  2024-01-03  Laptop             1       1200   Tabriz          1200
7  2024-01-04  Laptop             1       1200  Mashhad          1200


In [22]:
sales_above_two_qty = df[df['QuantitySold'] > 2]
print("Sales with Quantity Sold greater than 2:")
print(sales_above_two_qty)

Sales with Quantity Sold greater than 2:
         Date   Product  QuantitySold  UnitPrice     City  TotalRevenue
1  2024-01-01     Mouse             5         25   Tehran           125
2  2024-01-02  Keyboard             3         75  Mashhad           225
6  2024-01-04     Mouse             4         25   Shiraz           100


In [23]:
#__________________________________________________________________________________

In [24]:
# Weather Data Analysis Project

In [25]:
data = """Date,MaxTemp,MinTemp,Precipitation,Humidity
2024-07-01,32,20,0.5,65
2024-07-02,30,18,1.2,70
2024-07-03,NaN,22,0.1,60
2024-07-04,35,21,NaN,55
2024-07-05,28,15,2.0,80
2024-07-06,33,19,0.0,62
2024-07-07,31,NaN,0.3,68
2024-07-08,29,17,1.5,75
2024-07-09,NaN,20,0.0,60
2024-07-10,27,16,NaN,72"""

df_W = pd.read_csv(StringIO(data))


In [26]:
df_W

Date  MaxTemp  MinTemp  Precipitation  Humidity
0  2024-07-01     32.0     20.0            0.5        65
1  2024-07-02     30.0     18.0            1.2        70
2  2024-07-03      NaN     22.0            0.1        60
3  2024-07-04     35.0     21.0            NaN        55
4  2024-07-05     28.0     15.0            2.0        80
5  2024-07-06     33.0     19.0            0.0        62
6  2024-07-07     31.0      NaN            0.3        68
7  2024-07-08     29.0     17.0            1.5        75
8  2024-07-09      NaN     20.0            0.0        60
9  2024-07-10     27.0     16.0            NaN        72

In [27]:
#Handeling Missing Val
print("NaN values before filling:")
print(df_W.isnull().sum())
df_W = df_W.fillna(df_W.mean(numeric_only=True))
print("\nNaN values after filling:")
print(df_W.isnull().sum())
print("DataFrame after filling NaN:")
df_W

NaN values before filling:
Date             0
MaxTemp          2
MinTemp          1
Precipitation    2
Humidity         0
dtype: int64

NaN values after filling:
Date             0
MaxTemp          0
MinTemp          0
Precipitation    0
Humidity         0
dtype: int64
DataFrame after filling NaN:


Date  MaxTemp    MinTemp  Precipitation  Humidity
0  2024-07-01   32.000  20.000000            0.5        65
1  2024-07-02   30.000  18.000000            1.2        70
2  2024-07-03   30.625  22.000000            0.1        60
3  2024-07-04   35.000  21.000000            0.7        55
4  2024-07-05   28.000  15.000000            2.0        80
5  2024-07-06   33.000  19.000000            0.0        62
6  2024-07-07   31.000  18.666667            0.3        68
7  2024-07-08   29.000  17.000000            1.5        75
8  2024-07-09   30.625  20.000000            0.0        60
9  2024-07-10   27.000  16.000000            0.7        72

In [28]:
df_W['TempDifference'] = df_W['MaxTemp'] - df_W['MinTemp']
print("DataFrame with 'TempDifference' column:")
df_W

DataFrame with 'TempDifference' column:


Date  MaxTemp    MinTemp  Precipitation  Humidity  TempDifference
0  2024-07-01   32.000  20.000000            0.5        65       12.000000
1  2024-07-02   30.000  18.000000            1.2        70       12.000000
2  2024-07-03   30.625  22.000000            0.1        60        8.625000
3  2024-07-04   35.000  21.000000            0.7        55       14.000000
4  2024-07-05   28.000  15.000000            2.0        80       13.000000
5  2024-07-06   33.000  19.000000            0.0        62       14.000000
6  2024-07-07   31.000  18.666667            0.3        68       12.333333
7  2024-07-08   29.000  17.000000            1.5        75       12.000000
8  2024-07-09   30.625  20.000000            0.0        60       10.625000
9  2024-07-10   27.000  16.000000            0.7        72       11.000000

In [35]:
# Convert the 'Date' column to datetime objects and set it as the index
df_W['Date'] = pd.to_datetime(df_W['Date'])
df_W = df_W.set_index('Date')

monthly_average = df_W.resample('ME')[['MaxTemp', 'Precipitation']].mean()
print("Monthly Average Temperature and Precipitation:")
print(monthly_average)

KeyError: 'Date'

In [36]:
df_W

MaxTemp    MinTemp  Precipitation  Humidity  TempDifference
Date                                                                   
2024-07-01   32.000  20.000000            0.5        65       12.000000
2024-07-02   30.000  18.000000            1.2        70       12.000000
2024-07-03   30.625  22.000000            0.1        60        8.625000
2024-07-04   35.000  21.000000            0.7        55       14.000000
2024-07-05   28.000  15.000000            2.0        80       13.000000
2024-07-06   33.000  19.000000            0.0        62       14.000000
2024-07-07   31.000  18.666667            0.3        68       12.333333
2024-07-08   29.000  17.000000            1.5        75       12.000000
2024-07-09   30.625  20.000000            0.0        60       10.625000
2024-07-10   27.000  16.000000            0.7        72       11.000000

In [37]:
highest_precipitation_days = df_W.nlargest(5, 'Precipitation')
print("5 Days with Highest Precipitation:")
print(highest_precipitation_days)

5 Days with Highest Precipitation:
            MaxTemp  MinTemp  Precipitation  Humidity  TempDifference
Date                                                                 
2024-07-05     28.0     15.0            2.0        80            13.0
2024-07-08     29.0     17.0            1.5        75            12.0
2024-07-02     30.0     18.0            1.2        70            12.0
2024-07-04     35.0     21.0            0.7        55            14.0
2024-07-10     27.0     16.0            0.7        72            11.0


In [38]:
lowest_min_temp_days = df_W.nsmallest(5, 'MinTemp')
print("5 Days with Lowest Minimum Temperature:")
print(lowest_min_temp_days)

5 Days with Lowest Minimum Temperature:
            MaxTemp    MinTemp  Precipitation  Humidity  TempDifference
Date                                                                   
2024-07-05     28.0  15.000000            2.0        80       13.000000
2024-07-10     27.0  16.000000            0.7        72       11.000000
2024-07-08     29.0  17.000000            1.5        75       12.000000
2024-07-02     30.0  18.000000            1.2        70       12.000000
2024-07-07     31.0  18.666667            0.3        68       12.333333
